---
version: "3"
services:
  nodejs-app:
    build: .
    ports:
      - 9981:9981
    container_name: nodejsserver
    hostname: nodejsserver
    environment:
      MONGODB_URI: mongodb://mongo:27017/test
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
volumes:
  mongodb: {}
