version: '3'

services:
    nodejs-app:
        build: .
        ports:
            - 3000:3000 
        environment:
		    MONGODB_URI=mongodb://mongo:27017/
		depends_on:
            - mongo
			
    mongo:
        container_name: mongodb
        image: mongo
        volumes:
            - mongodb:/data/db
        ports:
            - 27017:27017
 volumes:
    mongodb: {} 
