apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsappcontainer
        image: dockerdevops1994/nodejs-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: mongodb://10.103.136.91:27017/test
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
spec:
  type: NodePort
  selector:
    app: nodejsapp
  ports:
  - port: 9981
    targetPort: 9981
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongors
spec:
  selector:
    matchLabels:
      app: mongo
  template:
     metadata:
       name: mongodbpod
       labels:
         app: mongo
     spec:
       containers:
       - name: mongodbcontainer
         image: mongo
         ports:
         - containerPort: 27017
         volumeMounts:
         - name: hostpathvol
           mountPath: /data/db
       volumes:
       - name: hostpathvol
         hostPath:
           path: /tmp/dbbackup
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
                               
