## NodeJs Application with service type NodePort and Mongo db POD with ClusterIP service ##

## Nodejs App

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsappdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsappcontainer
        image: dockerdevops1994/nodejs-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: mongodb://10.97.126.130:27017/test
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsapp
spec:
  type: NodePort
  selector:
    app: nodejsapp
  ports:
  - port: 9981
    targetPort: 9981
---

# Mongo db pod

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongors
spec:
  selector:
    matchLabels:
      app: mongo
  template:
     metadata:
       labels:
         app: mongo
     spec:
       containers:
       - name: mongodbcontainer
         image: mongo
         ports:
         - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
