apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejsapp.fullname" . }}
  labels:
    {{- include "nodejsapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nodejsapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nodejsapp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nodejsapp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
          - name: mongodb_root_user
            valueFrom:
              secretKeyRef:
                name: {{ include "nodejsapp.fullname" . }}
                key: mongodb_root_user
          - name: mongodb_root_password
            valueFrom:
              secretKeyRef:
                name: {{ include "nodejsapp.fullname" . }}
                key: mongodb_root_password
          - name: mongo_hostname
            valueFrom:
              configMapKeyRef:
                name: {{ include "nodejsapp.fullname" . }}
                key: mongo_hostname
          - name: MONGODB_URI
            value: mongodb://$(mongodb_root_user):$(mongodb_root_password)@$(mongo_hostname):27017/        
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
