apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodejsapp.fullname" . }}
  labels:
    {{- include "nodejsapp.labels" . | nindent 4 }}
type: Opaque
StringData:
  mongodb_root_user : root
  mongodb_root_password : root1234

